### ISSUE TITLE
<elocation_id> supported for references in Crossref schema

### ISSUE THREAD

**Issue by Melissa37** [elifesciences/elife-crossref-feed#138]
## Problem / Motivation
eLife and many other publishers produce online content yet, so the concept of page numbers to store bibliometric information about their articles and how to cite them is wrong.
Until now Crossref has not added ```<elocation_id>``` into their schema, which is a well-established element in JATS.
They have now added it and so when we send our bibliographic information about journal articles cited by the articles we publish, we can now send an ```<elocation_id>``` rather than cramming that information in ```<first_page>```

- WHO wants this?
Production

- WHEN and WHERE do they want it?
On conversion of content to deliver to Crossref, the JATS term ```<elocation-id>``` found in any ```<element-citation>``` should now be converted to ```<elocation_id>``` for the Crossref deposits rather than ```<first_page>```

- WHAT do they want?
In the Bot

- WHY do they want this?
It's good semantic tagging and helps ensure propagation of good clean metadata throughout the ecosystem.
I've been asking for this for 3 years and so happy it is finally implemented

## Proposed solution
For @gnott 

## Clarification needed and assumptions
This is currently for references only, I have an open question with them about eLife article elocation-ids, still to be answered.

---

## Tasks

- [x] Upgrade to deposit in Crossref schema version 4.4.1, which will be the default for this code project
- [x] Change `elocation_id` of citations to be placed into the `elocation_id` element in the Crossref deposit, instead of the `first_page` element
- [x] Update test cases
- [x] When this library is updated, we can integrate and deploy into the automated Crossref deposits infrastructure

**Comment by gnott** [comment]
I'm retaining the previous `first_page` tag if the Crossref schem is pre-4.4.1, so it will still produce valid output for all the supported Crossref schemas.

**Comment by gnott** [comment]
Code ready for review!

**Comment by gnott** [comment]
Everything seems right so I'm moving this forward. Will be merging and deploying in the `elife-bot` project and `elife-bot-formula` (where the Crossref schema version is specified as 4.4.1). We'll be depositing citation `<elocation_id>` values in the next day or so.

**Comment by gnott** [comment]
Deployed for eLife - done!
